# extras/dot_circleci_config-lesson_2_solution.yml

version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    resource_class: small                # default is large
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, world"
      - run: echo $PRACTICE_VARIABLE
  say-hi:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Hi there"      
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          context:
            - practice_context
      - say-hi
